
--CONTAINS -Permite buscar por una palabra
SELECT * FROM Person.Address A
WHERE CONTAINS(A.AddressLine1, '"first avenue"')

--CONTAINS - OPERADORES AND/AND NOT /OR
SELECT * FROM Person.Address A
--WHERE CONTAINS(A.AddressLine1, 'avenue AND port AND NOT 34')
WHERE CONTAINS(A.AddressLine1, 'avenue AND port')

--CONTAINS NEAR
SELECT * FROM Person.Address A
WHERE CONTAINS(A.AddressLine1, '"5415 San" NEAR dr')

SELECT * FROM Person.Address A
WHERE CONTAINS(A.AddressLine1, 'NEAR((21,central),6)')

SELECT * FROM Person.Address A --ORDER BY LEN(AddressLine1)
WHERE CONTAINS(A.AddressLine1, 'NEAR((hilton,factory,25),5)')

--CONTAINS FORMSOF INFLETIONAL (SUSTANTIVOS)
SELECT * FROM Person.Address A
WHERE CONTAINS(A.AddressLine1, 'FORMSOF(INFLECTIONAL, "avenues")')

--FORMSOF INFLECTIONAL (verbos)
SELECT * FROM Person.Address A
WHERE CONTAINS(A.AddressLine1, 'FORMSOF(INFLECTIONAL, "EE")', LANGUAGE 3082) 

--OBTENER TODOS LOS TIEMPOS VERBALES DE UN VERBO
SELECT display_term
WHERE SYS.DM_FTS_PARSER('FORMSOF(INFLECTIONAL, saltar)', 3082, 0, 0) 

--FREETEXT
SELECT * FROM Person.Address A
WHERE FREETEXT(A.AddressLine1,'"825 99828 routh"')

--POPULATION DE UNA TABLA
ALTER FULLTEXT INDEX ON Person.address START FULL POPULATION
ALTER FULLTEXT INDEX ON Person.address START UPDATE POPULATION